import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { createClient } from "next-sanity"
import imageUrlBuilder from '@sanity/image-url'


export default function Home({authors,category}) {

  const client = createClient({
    projectId: "iuh30fxh",
    dataset: "production",
    apiVersion: '2021-10-21',
    useCdn: true
  });
  const builder = imageUrlBuilder(client)
  console.log(authors)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <h1>Nasir</h1>
     {/* <h1>Author :{authors[0]._id}</h1> */}
     <h1>category :{category[0].title}</h1>
     <Image src={builder.image(authors[1].image).url() || "Nasir.jpg"}  width={125} height={125} alt="Picture" className='rounded-full'/>

    </div>
  )
}

export async function getServerSideProps() {
  const client = createClient({
    projectId: "iuh30fxh",
    dataset: "production",
    apiVersion: '2021-10-21',
    useCdn: true
  });
  const authors = await client.fetch(`*[_type == "author"]`);
  const category = await client.fetch(`*[_type == "category"]`);

  return {
    props: {
      authors,category
    }
  };
}